<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create Staff' => '@@Thêm mới nhân viên@@',
    'List staff' => '@@Danh sách nhân viên@@',
    'Nation' => '@@Dân tộc@@',
    'Select day of birth' => '@@Lựa chọn ngày sinh@@',
    'Update Staff: ' => '@@Capaj nhật nhân viên@@',
    'date ò birth' => '@@Ngày sinh@@',
    ' Create' => 'Thêm mới',
    ' Key information' => 'Thông tin chính',
    ' Reset' => 'Làm mới',
    ' Subsidiary information' => 'Thông tin phụ',
    'Address' => 'Địa chỉ',
    'Certificate Number' => 'Số chứng minh nhân dân',
    'City' => 'City',
    'Coefficients Salary' => 'Hệ số lương',
    'Create' => 'Thêm mới',
    'Create List Department' => 'Tạo mới khoa',
    'Create Rank' => 'Tạo mới trình độ',
    'Create Regency' => 'Thêm mới chức vụ',
    'Day Birth' => 'Ngày sinh',
    'Department' => 'Khoa',
    'Department Details' => 'Chi tiết khoa',
    'Dormitory' => 'Kí túc xá',
    'Fullname' => 'Họ và tên',
    'Girl' => 'Nữ',
    'Home Town' => 'Quê quán',
    'ID' => 'Mã ',
    'Id Dormitory' => 'Mã kí túc xá',
    'Id Nation' => 'Mã dân tộc',
    'Id Regency' => 'Chức vụ',
    'Id Staff' => 'Mã nhân viên',
    'Imager' => 'Ảnh đại diện',
    'Layer Number' => 'Số tầng',
    'List Class' => 'Danh sách lớp',
    'List Departments' => 'Danh sách khoa',
    'List Dormitory' => 'Danh sách kí túc xá',
    'List Staff' => 'Danh sách nhân viên',
    'List Student' => 'Danh sách học sinh',
    'List class Details' => 'Chi tiết lớp',
    'Men' => 'Nam',
    'Name' => 'Tên',
    'Name Dormitory' => 'Tên kí túc xá',
    'Name Rank' => 'Tên trình độ',
    'Rank' => 'Trình độ',
    'Regencies' => 'Danh sách chức vụ',
    'Regency' => 'Chức vụ',
    'Regency Details' => 'Chi tiết chức vụ',
    'Reset' => 'Làm mới',
    'Select Nation' => 'Lựa chọn dân tộc',
    'Select Regency' => 'Lựa chọn chức vụ',
    'Select Sex' => 'Lựa chọn giới tính',
    'Select a dormitory ...' => 'Chọn kí túc xá',
    'Select rank' => 'Lựa chọn cấp học',
    'Sex' => 'Giới tính',
    'Staff Details' => 'Chi tiết nhân viên',
    'Status' => 'Trạng thái',
    'Update' => 'Cập nhật',
    'Update List Department: ' => 'Cập nhật khoa',
    'Update Rank: ' => 'Cập nhật trình độ',
    'Women' => 'Nữ',
    'birthplace' => 'Nơi sinh',
    'date of birth' => 'ngày sinh',
    'farther name' => 'Tên của bố',
    'fist name' => 'tên',
    'full name' => 'họ và tên',
    'hometown' => 'Quê quán',
    'id department' => 'Mã khoa',
    'id nation' => 'Mã dân tộc',
    'id regency' => 'Số thứ tự chức vụ',
    'id staff' => 'mã nhân viên',
    'id student' => 'Mã học sinh',
    'last name' => 'Họ đệm',
    'name department' => 'Tên khoa',
    'name nation' => 'Tên dân tộc',
    'name rank' => 'Tên bậc',
    'name regency' => 'Tên chức vụ',
    'picture' => 'Ảnh',
    'religiousness' => 'Tôn giáo',
    'status' => 'Trạng thái',
    'through class' => 'qua lớp',
    'women' => 'Nữ',
];
