<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' Create' => '',
    ' Key information' => '',
    ' Reset' => '',
    ' Subsidiary information' => '',
    'Certificate Number' => '',
    'City' => '',
    'Coefficients Salary' => '',
    'Create' => '',
    'Create List Department' => '',
    'Create Rank' => '',
    'Create Regency' => '',
    'Department' => '',
    'Department Details' => '',
    'Girl' => '',
    'ID' => '',
    'Id Dormitory' => '',
    'Id Nation' => '',
    'Id Regency' => '',
    'Id Staff' => '',
    'Layer Number' => '',
    'List Class' => '',
    'List Departments' => '',
    'List Dormitory' => '',
    'List Staff' => '',
    'List Student' => '',
    'List class Details' => '',
    'Men' => '',
    'Name' => '',
    'Name Dormitory' => '',
    'Name Rank' => '',
    'Rank' => '',
    'Regencies' => '',
    'Regency' => '',
    'Regency Details' => '',
    'Reset' => '',
    'Select Nation' => '',
    'Select Regency' => '',
    'Select Sex' => '',
    'Select a dormitory ...' => '',
    'Select rank' => '',
    'Sex' => '',
    'Staff Details' => '',
    'Status' => '',
    'Update' => '',
    'Update List Department: ' => '',
    'Update Rank: ' => '',
    'Women' => '',
    'birthplace' => '',
    'date of birth' => '',
    'farther name' => '',
    'fist name' => '',
    'full name' => '',
    'hometown' => '',
    'id department' => '',
    'id nation' => '',
    'id regency' => '',
    'id staff' => '',
    'id student' => '',
    'last name' => '',
    'name department' => '',
    'name nation' => '',
    'name rank' => '',
    'name regency' => '',
    'picture' => '',
    'religiousness' => '',
    'status' => '',
    'through class' => '',
    'women' => '',
    'Create Staff' => '@@@@',
    'List staff' => '@@@@',
    'Nation' => '@@@@',
    'Select day of birth' => '@@@@',
    'Update Staff: ' => '@@@@',
    'date ò birth' => '@@@@',
    'Address' => '@@@@',
    'Day Birth' => '@@@@',
    'Dormitory' => '@@@@',
    'Fullname' => '@@@@',
    'Home Town' => '@@@@',
    'Imager' => '@@@@',
];
